workspace = { members = ["broker", "dll", "injector"], resolver="2" }

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false


